"""add tables

Revision ID: bc953d72654e
Revises: 
Create Date: 2024-09-14 10:46:38.310943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc953d72654e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('NAME', sa.String(length=100), nullable=False),
    sa.Column('LATITUDE', sa.Float(), nullable=False),
    sa.Column('LONGITUDE', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='db'
    )
    op.create_table('weather',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('TEMPERATURE', sa.Float(), nullable=False),
    sa.Column('TIMESTAMP', sa.DateTime(), nullable=False),
    sa.Column('site', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['site'], ['db.site.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='db'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weather', schema='db')
    op.drop_table('site', schema='db')
    # ### end Alembic commands ###
