name: api-wf
on:
  push:
    tags:
      - 'v*.*.*'
    branches:
    - "main"
    paths:
      - "app/**"
      - ".github/workflows/app-**"
  pull_request:
    branches:
    - "*"
    paths:
      - "app/**"
      - ".github/workflows/app-**"

env:
  POETRY_VERSION: "1.8.3"
  PYTHON_VERSION: "3.12"

jobs:
  test:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ./app
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Setup poetry
        run: |
          curl -sSL https://install.python-poetry.org | POETRY_VERSION=${{ env.POETRY_VERSION }} python -
          poetry lock
      - name: Install dependencies
        run: |
          poetry install
      - name: Ruff Format
        run: |
          poetry run ruff check
      - name: Run tests
        run: |
          poetry run pytest -v
    
  build-be:
    runs-on: ubuntu-22.04
    needs: [test]
    if: github.event_name != 'pull_request'
    steps:
      - uses: actions/checkout@v4
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: app
          file: ./app/migrations.Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/bee-api-migrations:${{ startsWith(github.ref, 'refs/tags/v') && github.ref_name || 'develop' }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: app
          file: ./app/app.Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/bee-api:${{ startsWith(github.ref, 'refs/tags/v') && github.ref_name || 'develop' }}